/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface WcTrombone {}
}

declare global {


  interface HTMLWcTromboneElement extends Components.WcTrombone, HTMLStencilElement {}
  var HTMLWcTromboneElement: {
    prototype: HTMLWcTromboneElement;
    new (): HTMLWcTromboneElement;
  };
  interface HTMLElementTagNameMap {
    'wc-trombone': HTMLWcTromboneElement;
  }
}

declare namespace LocalJSX {
  interface WcTrombone extends JSXBase.HTMLAttributes<HTMLWcTromboneElement> {}

  interface IntrinsicElements {
    'wc-trombone': WcTrombone;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


